baseURL = 'https://msam2026.github.io/'
languageCode = 'en-us'
title = 'MSAM - From Molecules to Cells'
theme = 'ananke'

[params]
  description = "International Workshop on Multiscale Simulation and AI-Driven Modeling for Biomolecular Systems"
  favicon = ""
  site_logo = ""
  background_color_class = "bg-dark-blue"
  featured_image = "/images/header.jpg"
  recent_posts_number = 0
  body_classes = "avenir bg-near-white"
